export const PROMPTS = [
  { id: "people-arrival", theme: "People", title: "Follow an arrival", question: "Choose a person from your project. What do they notice, need, or wonder about on arrival?", exercise: "Draw a six-frame sequence tracing their movement through the space. Annotate a moment of spatial uncertainty and a moment that creates a sense of welcome." },
  { id: "people-meeting", theme: "People", title: "Space to connect and pause", question: "Where might people want to gather, and where might someone want to be alone?", exercise: "Sketch three spatial arrangements that explore the relationship between a communal and a quiet place." },
  { id: "site-edge", theme: "Site", title: "Work with an edge", question: "Which boundary or feature of the site could become a starting point?", exercise: "Sketch three spatial responses to the edge: align with it, intersect it, and set back from it." },
  { id: "site-ground", theme: "Site", title: "Engage the terrain", question: "What possibilities emerge if your project sits on, above, or partly within the ground?", exercise: "Sketch three sectional strategies. Annotate confirmed site conditions and assumptions that need further verification." },
  { id: "light-sequence", theme: "Light", title: "Move through light", question: "How might a change in light help express the experience you want?", exercise: "Draw a sequence of three spaces using only light and dark shading. Record orientation assumptions." },
  { id: "light-opening", theme: "Light", title: "Change one opening", question: "What could change if the same room received light from above, beside, or through a screen?", exercise: "Keep the room constant and sketch three opening arrangements in section." },
  { id: "movement-path", theme: "Movement", title: "Find more than one path", question: "Could movement be direct, looping, or a series of pauses?", exercise: "Draw three path diagrams between the same arrival and destination. Note whom each path serves." },
  { id: "movement-threshold", theme: "Movement", title: "Design a transition", question: "Where should someone feel they are entering a different kind of space?", exercise: "Sketch a transition using changes in height, enclosure, or view. Explain the intended effect." },
  { id: "material-rule", theme: "Material", title: "Start with a making rule", question: "What spatial possibilities could come from folding, stacking, or weaving?", exercise: "Choose one operation and make three paper studies. Note a useful space in each." },
  { id: "material-contrast", theme: "Material", title: "Explore a contrast", question: "How might a relationship such as heavy/light or rough/smooth support your concept?", exercise: "Sketch the same gathering place with three material relationships. Describe what each invites." },
] as const;

export const THEMES = ["People", "Site", "Light", "Movement", "Material"] as const;
