// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import StudioBrainstorm from "../StudioBrainstorm";
import StudioDemo from "./StudioDemo";
import { demoExport, normalizeDemo } from "./demo";
import { downloadText } from "./inspiration";
vi.mock("./inspiration", async importOriginal => ({ ...await importOriginal<typeof import("./inspiration")>(), downloadText: vi.fn() }));
beforeEach(() => { localStorage.clear(); vi.clearAllMocks(); });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
const next = () => fireEvent.click(screen.getByRole("button", { name: "Next step" }));
it("walks through the demo from architecture learning, exports feedback and preserves the real project without network calls", () => {
  const fetch = vi.fn(); vi.stubGlobal("fetch", fetch);
  const original = JSON.stringify({ title: "My actual project", brief: "Keep my brief" });
  localStorage.setItem("studio-brainstorm:v1:guest", original);
  render(<StudioBrainstorm ownerId="guest" learningMode />);
  fireEvent.click(screen.getByRole("button", { name: "Start professor demo" }));
  expect(screen.getByRole("button", { name: "Next step" })).toBeDisabled();
  expect(screen.getByRole("button", { name: "4. Explore a diagram" })).toBeDisabled();
  fireEvent.click(screen.getByLabelText("I compared the example requirements with the brief.")); next();
  fireEvent.click(screen.getByRole("button", { name: "Circulation and arrival" }));
  fireEvent.change(screen.getByLabelText(/Student reflection/), { target: { value: "Separate noisy and quiet paths" } }); next();
  fireEvent.click(screen.getByRole("button", { name: "Explore connecting spine" })); next();
  expect(screen.getByRole("img").getAttribute("aria-label")).toContain("Connecting spine");
  fireEvent.click(screen.getByLabelText("Show possible arrival connections"));
  expect(screen.getByRole("img").getAttribute("aria-label")).not.toContain("with possible arrival connections");
  fireEvent.change(screen.getByLabelText(/What would you change/), { target: { value: "Add a quiet threshold" } }); next();
  fireEvent.change(screen.getByLabelText("What should we change first for your studio?"), { target: { value: "Use our next assignment" } });
  fireEvent.click(screen.getByRole("button", { name: "Download demo notes and feedback" }));
  expect(downloadText).toHaveBeenCalledWith(expect.stringContaining("Use our next assignment"), "studio-professor-feedback.txt", "text/plain");
  expect(vi.mocked(downloadText).mock.calls[0][0]).toContain("Separate noisy and quiet paths");
  fireEvent.click(screen.getByRole("button", { name: "Open my assignment workspace" }));
  expect(screen.getByLabelText("Assignment brief (required)")).toHaveValue("Keep my brief");
  expect(localStorage.getItem("studio-brainstorm:v1:guest")).toBe(original);
  expect(fetch).not.toHaveBeenCalled();
});
it("restores only the current owner's demo and safely handles corrupt saved values", () => {
  localStorage.setItem("studio-professor-demo:v1:alice", JSON.stringify({ reviewed: true, direction: 2, change: "Alice feedback" }));
  const view = render(<StudioDemo ownerId="alice" onFinish={() => {}} />);
  fireEvent.click(screen.getByRole("button", { name: "5. Professor feedback" }));
  expect(screen.getByLabelText("What should we change first for your studio?")).toHaveValue("Alice feedback");
  view.unmount(); localStorage.setItem("studio-professor-demo:v1:bob", "bad json");
  render(<StudioDemo ownerId="bob" onFinish={() => {}} />);
  expect(screen.getByText(/could not be restored/)).toBeInTheDocument();
  expect(screen.getByRole("button", { name: "Next step" })).toBeDisabled();
  expect(normalizeDemo({ topic: 999, direction: -1, reflection: {}, reviewed: "yes" })).toMatchObject({ topic: 0, direction: 0, reflection: "", reviewed: false });
});
it("keeps feedback usable for export when browser storage fails", () => {
  render(<StudioDemo ownerId="guest" onFinish={() => {}} />);
  const spy = vi.spyOn(Storage.prototype, "setItem").mockImplementation(() => { throw new Error("Quota"); });
  fireEvent.click(screen.getByLabelText("I compared the example requirements with the brief."));
  expect(screen.getByText(/Browser storage is unavailable/)).toBeInTheDocument();
  fireEvent.click(screen.getByRole("button", { name: "5. Professor feedback" }));
  fireEvent.change(screen.getByLabelText("What helped the student get started?"), { target: { value: "Visible trade-offs" } });
  fireEvent.click(screen.getByRole("button", { name: "Download demo notes and feedback" }));
  expect(downloadText).toHaveBeenCalledWith(expect.stringContaining("Visible trade-offs"), expect.any(String), expect.any(String));
  expect(demoExport(normalizeDemo(null))).toContain("no live AI generation");
  spy.mockRestore();
});
